[[redirects]]
  from = "/en/buidl.html"
  to = "/en/buidl/"
  status = 301
  force = true

[[redirects]]
  from = "/fr/buidl.html"
  to = "/fr/buidl/"
  status = 301
  force = true

[[redirects]]
  from = "/buidl.html"
  to = "/fr/buidl/"
  status = 301
  force = true
