#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Script de traduction Phase 2 pour index_en.html (Sections 3-6)
"""

import re

def main():
    print("🚀 Démarrage de la traduction Phase 2 (Sections 3-6)...")
    try:
        with open('index_en.html', 'r', encoding='utf-8') as f:
            content = f.read()
    except FileNotFoundError:
        print("❌ Fichier index_en.html introuvable.")
        return

    replacements = [
        # SECTION 3: TYPES DE TOKENS
        (r'Les Types de Tokens', 'Token Types'),
        (r'Comprendre les différentes catégories d\'actifs numériques', 'Understanding the different categories of digital assets'),
        (r'Utility Tokens', 'Utility Tokens'), # Identique, mais pour contexte
        (r'Fonction :', 'Function:'),
        (r'Donnent accès à des services ou fonctionnalités spécifiques au sein d\'un\s+écosystème blockchain\.', 
         'Provide access to specific services or features within a blockchain ecosystem.'),
        (r'Exemple :', 'Example:'),
        (r'Tokens pour utiliser une plateforme de stockage décentralisé, payer des\s+frais de transaction, ou accéder à une application\.', 
         'Tokens to use a decentralized storage platform, pay transaction fees, or access an application.'),
        
        (r'Security Tokens', 'Security Tokens'),
        (r'Représentent la propriété d\'actifs réels \(actions, obligations,\s+immobilier\)\.', 
         'Represent ownership of real assets (equity, bonds, real estate).'),
        (r'Régulation :', 'Regulation:'),
        (r'Soumis aux régulations financières traditionnelles\. Offrent des droits\s+similaires aux titres financiers classiques\.', 
         'Subject to traditional financial regulations. Offer rights similar to classic financial securities.'),
        
        (r'Governance Tokens', 'Governance Tokens'),
        (r'Permettent aux détenteurs de participer aux décisions concernant\s+l\'évolution d\'un protocole\.', 
         'Allow holders to participate in decisions regarding the protocol\'s evolution.'),
        (r'Pouvoir :', 'Power:'),
        (r'Vote sur les modifications, allocation de trésorerie, partenariats\s+stratégiques dans les DAO \(Organisations Autonomes Décentralisées\)\.', 
         'Vote on modifications, treasury allocation, strategic partnerships in DAOs (Decentralized Autonomous Organizations).'),

        # SECTION 4: TYPES DE TOKENISATION
        (r'Les Types de Tokenisation', 'Tokenization Types'),
        (r'Comment créer de la valeur numérique', 'How to create digital value'),
        (r'La tokenisation représente une révolution dans la représentation numérique des actifs\. Ce processus\s+permet de transformer pratiquement n\'importe quel actif du monde réel en un token numérique sur une\s+blockchain, ouvrant ainsi des possibilités infinies pour la finance moderne\.', 
         'Tokenization represents a revolution in the digital representation of assets. This process allows transforming virtually any real-world asset into a digital token on a blockchain, opening infinite possibilities for modern finance.'),
        
        (r'Asset-Backed Tokens', 'Asset-Backed Tokens'),
        (r'Tokens adossés à des actifs réels tangibles', 'Tokens backed by tangible real-world assets'),
        (r'Stablecoins adossés à des monnaies fiat \(USD, EUR\)', 'Stablecoins backed by fiat currencies (USD, EUR)'),
        (r'Tokens immobiliers représentant des parts de propriétés', 'Real estate tokens representing property shares'),
        (r'Tokens obligataires liés à des titres de dette', 'Bond tokens linked to debt securities'),
        (r'Tokens adossés à des matières premières \(or, pétrole\)', 'Tokens backed by commodities (gold, oil)'),
        
        (r'Tokens donnant accès à des services', 'Tokens providing access to services'),
        (r'Paiement des frais de transaction sur une blockchain', 'Payment of transaction fees on a blockchain'),
        (r'Accès à une application décentralisée', 'Access to a decentralized application'),
        (r'Utilisation d\'un protocole DeFi pour emprunter ou prêter', 'Use of a DeFi protocol for borrowing or lending'),
        (r'Droit d\'utiliser une API ou un service cloud décentralisé', 'Right to use an API or decentralized cloud service'),
        
        (r'Revenue-Sharing Tokens', 'Revenue-Sharing Tokens'),
        (r'Tokens distribuant une partie des revenus', 'Tokens distributing a share of revenue'),
        (r'Partage automatique des frais de transaction prélevés', 'Automatic sharing of collected transaction fees'),
        (r'Rémunération basée sur le volume d\'activité du protocole', 'Remuneration based on protocol activity volume'),
        (r'Distribution des profits générés par le pool de liquidités', 'Distribution of profits generated by the liquidity pool'),
        (r'Dividendes automatiques via smart contracts', 'Automatic dividends via smart contracts'),
        
        (r'Staking Tokens', 'Staking Tokens'),
        (r'Tokens permettant de sécuriser le réseau', 'Tokens allowing network security'),
        (r'Blockchains Proof of Stake \(Ethereum, Cardano, Polkadot\)', 'Proof of Stake Blockchains (Ethereum, Cardano, Polkadot)'),
        (r'Protocoles DeFi offrant des rendements sur liquidités', 'DeFi protocols offering yields on liquidity'),
        (r'Programmes de yield farming', 'Yield farming programs'),
        (r'Validation de transactions dans les réseaux décentralisés', 'Transaction validation in decentralized networks'),
        
        (r'Tokens donnant un pouvoir de décision', 'Tokens giving decision-making power'),
        (r'Ajustement des frais et paramètres économiques', 'Adjustment of fees and economic parameters'),
        (r'Ajout de nouvelles fonctionnalités', 'Addition of new features'),
        (r'Allocation de la trésorerie du projet', 'Project treasury allocation'),
        (r'Partenariats stratégiques et modifications du code', 'Strategic partnerships and code modifications'),

        (r'Avantages Mesurables de la Tokenisation', 'Measurable Benefits of Tokenization'),
        (r'Réduction des coûts opérationnels', 'Operational cost reduction'),
        (r'Exécution vs plusieurs jours', 'Execution vs several days'),
        (r'Erreurs humaines', 'Human errors'),
        (r'Traçabilité complète', 'Complete traceability'),
        (r'Secondes', 'Seconds'),

        # SECTION 5: ALIMENTATION DES TOKENS
        (r'Comment un Token est « Alimenté » \?', 'How is a Token "Powered"?'),
        (r'Les mécanismes qui créent la valeur d\'un token', 'Mechanisms creating token value'),
        (r'Concept Fondamental', 'Fundamental Concept'),
        (r'Un token n\'a pas de valeur par défaut\. Contrairement à une monnaie traditionnelle soutenue par un\s+État ou une banque centrale, la valeur d\'un token provient entièrement de <strong>mécanismes\s+économiques précis</strong> intégrés dans son architecture\.', 
         'A token has no default value. Unlike traditional currency backed by a State or Central Bank, a token\'s value derives entirely from <strong>precise economic mechanisms</strong> embedded in its architecture.'),
        (r'Utility \(Utilité\)', 'Utility'),
        (r'Le token donne accès à un service ou une fonctionnalité', 'Token gives access to a service or feature'),
        (r'Revenue-Sharing \(Partage de Revenus\)', 'Revenue-Sharing'),
        (r'Le token distribue une partie des revenus générés', 'Token distributes part of generated revenue'),
        (r'Asset-Backed \(Adossement à des Actifs\)', 'Asset-Backed'),
        (r'Le token est garanti par un actif réel', 'Token is collateralized by a real asset'),
        (r'Staking \(Mise en Jeu\)', 'Staking'),
        (r'Le token génère des récompenses en étant verrouillé', 'Token generates rewards by being locked'),
        (r'Governance \(Gouvernance\)', 'Governance'),
        (r'Le token donne un pouvoir de décision', 'Token gives decision-making power'),
        (r'Scarcity \(Rareté\)', 'Scarcity'),
        (r'La valeur vient de l\'offre limitée', 'Value comes from limited supply'),
        (r'Supply cap :', 'Supply cap:'),
        (r'Offre maximale définie \(21M pour Bitcoin\)', 'Defined maximum supply (21M for Bitcoin)'),
        (r'Burn de tokens :', 'Token Burn:'),
        (r'Destruction régulière via les frais', 'Regular destruction via fees'),
        (r'Halving :', 'Halving:'),
        (r'Réduction progressive de l\'émission', 'Progressive issuance reduction'),
        (r'Inflation contrôlée :', 'Controlled Inflation:'),
        (r'Émission décroissante programmée', 'Programmed decreasing issuance'),

        # SECTION 6: CYCLE DE VIE
        (r'Cycle de Vie Complet d\'un Token', 'Complete Token Lifecycle'),
        (r'De la conception à l\'extinction : comprendre toutes les étapes', 'From conception to extinction: understanding all steps'),
        
        # Ce pattern est une liste partielle, il faudra peut-être vérifier le contenu réel
    ]

    count = 0
    content_modified = content
    for pattern, replacement in replacements:
        new_content = re.sub(pattern, replacement, content_modified, flags=re.DOTALL | re.IGNORECASE)
        if new_content != content_modified:
            content_modified = new_content
            count += 1
            print(f"✅ Remplacé : {replacement[:30]}...")
    
    with open('index_en.html', 'w', encoding='utf-8') as f:
        f.write(content_modified)
    
    print(f"\n🎉 Traduction Phase 2 terminée : {count} blocs corrigés.")

if __name__ == "__main__":
    main()
