import re
import os

FILE_PATH = '/Users/joanl/blockchain-presentation/en/methodology.html'

REPLACEMENTS = [
    (r'Méthodologie &amp; Scoring', 'Methodology &amp; Scoring'),
    (r'Transparence et rigueur\. Découvrez comment nos algorithmes évaluent le risque et la maturité des actifs numériques\.', 'Transparency and rigor. Discover how our algorithms assess the risk and maturity of digital assets.'),
    (r'Rigueur <span\n                style="color:#3b82f6">Analytique</span>', 'Analytical <span style="color:#3b82f6">Rigor</span>'),
    (r'Cadre méthodologique et algorithmique de la plateforme DCM Digital\.', 'Methodological and algorithmic framework of the DCM Digital platform.'),
    (r'>Sommaire<', '>Table of Contents<'),
    (r'Avertissement Légal', 'Legal Disclaimer'),
    (r'Algorithme DCM Score', 'DCM Score Algorithm'),
    (r'Dimensions d\'analyse', 'Analysis Dimensions'),
    (r'Gestion de la donnée', 'Data Management'),
    (r'Études de Cas', 'Case Studies'),
    (r'Validité &amp; Limites', 'Validity &amp; Limits'),
    (r'Modèle de Gouvernance', 'Governance Model'),
    (r'Note aux Institutionnels', 'Note to Institutionals'),
    (r'DCM Digital est une plateforme Decision Intelligence\. Les scores générés par nos algorithmes\s+sont\s+des indicateurs de maturité relative et de résilience technique\. Ils ne constituent pas des\s+conseils\s+financiers, juridiques ou bancaires\.', 'DCM Digital is a Decision Intelligence platform. The scores generated by our algorithms are indicators of relative maturity and technical resilience. They do not constitute financial, legal, or banking advice.'),
    (r'L\'Algorithme DCM Score V2', 'The DCM Score V2 Algorithm'),
    (r'Le <strong>Decision Maturity Score</strong> est calculé via une agrégation multicritères pondérée\.\s+Chaque indicateur brut est normalisé sur une échelle de 0 à 100 via un algorithme de\s+<em>Min-Max Scaling</em> pour assurer la comparabilité inter-projets\.', 'The <strong>Decision Maturity Score</strong> is calculated via a weighted multi-criteria aggregation. Each raw indicator is normalized on a scale of 0 to 100 via a <em>Min-Max Scaling</em> algorithm to ensure cross-project comparability.'),
    (r'Où T=Technique, J=Juridique, M=Marché, E=ESG', 'Where T=Technical, J=Legal, M=Market, E=ESG'),
    (r'Processus de Normalisation &amp; Calibration', 'Normalization &amp; Calibration Process'),
    (r'Pour éviter les biais statistiques, nous appliquons une fonction sigma sur les variables de volume\s+et de volatilité, transformant les données brutes hétérogènes en un indice de confiance linéaire\.\s+Ce modèle est inspiré des méthodologies standards de crédit comme le <strong>Altman Z-Score</strong>\s+pour la probabilité de défaut, adapté aux contraintes de liquidité on-chain\.', 'To avoid statistical biases, we apply a sigma function to volume and volatility variables, transforming heterogeneous raw data into a linear confidence index. This model is inspired by standard credit methodologies such as the <strong>Altman Z-Score</strong> for the probability of default, adapted to on-chain liquidity constraints.'),
    (r'Consulter le Backtesting Historique', 'View Historical Backtesting'),
    (r'Dimensions d\'Analyse Stratégique', 'Strategic Analysis Dimensions'),
    (r'Technique <span class="weight-badge">', 'Technical <span class="weight-badge">'),
    (r'Complexité du code, audits CertiK/OpenZeppelin, décentralisation des\s+séquenceurs et immuabilité\.', 'Code complexity, CertiK/OpenZeppelin audits, sequencer decentralization, and immutability.'),
    (r'Juridique <span class="weight-badge">', 'Legal <span class="weight-badge">'),
    (r'Compatibilité MiCA Articles 12-14, conformité GDPR des logs et\s+structures de transfert légal\.', 'MiCA Articles 12-14 compatibility, GDPR log compliance, and legal transfer structures.'),
    (r'Marché <span class="weight-badge">', 'Market <span class="weight-badge">'),
    (r'Profondeur de liquidité sur DEX/CEX, volume on-chain et stabilité du\s+peg \(pour RWAs stables\)\.', 'Liquidity depth on DEX/CEX, on-chain volume, and peg stability (for stable RWAs).'),
    (r'> ESG <span class="weight-badge">', '> ESG <span class="weight-badge">'),
    (r'Consommation KWh/Tx, diversité des validateurs et alignement avec les\s+standards de reporting extra-financier\.', 'KWh/Tx consumption, validator diversity, and alignment with non-financial reporting standards.'),
    (r'Architecture de Données', 'Data Architecture'),
    (r'L\'intégrité de l\'analyse repose sur le croisement de trois vecteurs d\'information :', 'The integrity of the analysis relies on the intersection of three information vectors:'),
    (r'Flux Temps-Réel \(60s\) :', 'Real-Time Data (60s):'),
    (r'Agrégateurs de spreads et de\s+volumes via APIs REST institutionnelles\.', 'Spread and volume aggregators via institutional REST APIs.'),
    (r'Moteur On-Chain :', 'On-Chain Engine:'),
    (r'Analyse heuristique des smart\s+contracts \(Ethereum, Polygon, Base VM\)\.', 'Heuristic analysis of smart contracts (Ethereum, Polygon, Base VM).'),
    (r'Base Stratégique :', 'Strategic Base:'),
    (r'Données qualitatives auditées par\s+nos experts \(validité des licences CASP\)\.', 'Qualitative data audited by our experts (CASP license validity).'),
    (r'Études de Cas Comparatives', 'Comparative Case Studies'),
    (r'>Projet<', '>Project<'),
    (r'>Facteur Clé<', '>Key Factor<'),
    (r'>Statut<', '>Status<'),
    (r'Conformité MiCA totale', 'Full MiCA compliance'),
    (r'Liquidité secondaire limitée', 'Limited secondary liquidity'),
    (r'Incertitude Juridique', 'Legal Uncertainty'),
    (r'Alignement Réglementaire &amp; Banking\s+Standards', 'Regulatory Alignment &amp; Banking Standards'),
    (r'Mapping de la taxonomie DCM vers les cadres prudentiels internationaux\.', 'Mapping the DCM taxonomy to international prudential frameworks.'),
    (r'Objectif Prudentiel', 'Prudential Objective'),
    (r'Résilience opérationnelle digitale', 'Digital operational resilience'),
    (r'Capacité de sortie sous stress \(30j\)', 'Exit capacity under stress (30 days)'),
    (r'Réduction de l\'exposition en défaut', 'Reduction of default exposure'),
    (r'Validité &amp; Limites de la Méthode', 'Validity &amp; Limits of the Method'),
    (r'Malgré une rigueur statistique maximale, toute modélisation comporte des limites :', 'Despite maximum statistical rigor, any modeling has limits:'),
    (r'Latence Réglementaire :', 'Regulatory Latency:'),
    (r'Les scores juridiques peuvent varier après un\s+changement législatif soudain\.', 'Legal scores may vary after a sudden legislative change.'),
    (r'Volatilité :', 'Volatility:'),
    (r'Les métriques de marché sont volatiles par nature\.', 'Market metrics are volatile by nature.'),
    (r'Corrélation :', 'Correlation:'),
    (r'Une faille technique \(T\) impacte souvent directement la liquidité\s+\(M\)\.', 'A technical flaw (T) often directly impacts liquidity (M).'),
    (r'Bibliographie &amp; Standards', 'Bibliography &amp; Standards'),
    (r'Explication scientifique de l\'algorithme de scoring DCM : Technique, Juridique, Marché et ESG pour la finance tokenisée\.', 'Scientific explanation of the DCM scoring algorithm: Technical, Legal, Market, and ESG for tokenized finance.'),
]

def main():
    if not os.path.exists(FILE_PATH):
        print("File not found.")
        return
        
    with open(FILE_PATH, 'r', encoding='utf-8') as f:
        content = f.read()
        
    for p, repl in REPLACEMENTS:
        content = re.sub(p, repl, content, flags=re.IGNORECASE)
        
    with open(FILE_PATH, 'w', encoding='utf-8') as f:
        f.write(content)
    print("Methodology page translated.")

if __name__ == '__main__':
    main()
